const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
    cadastrarAluno: (dados: any) => ipcRenderer.invoke("cadastrar-aluno", dados),
    cadastrarLivro: (dados: any) => ipcRenderer.invoke("cadastrar-um-livro", dados),
    cadastrarEmprestimo: (dados:any) => ipcRenderer.invoke("cadastrar-emprestimo", dados),
    obterAlunos: () => ipcRenderer.invoke("obter-alunos"),
    obterLivros: () => ipcRenderer.invoke("obter-livros"),
    obterEmprestimo: () => ipcRenderer.invoke("obter-emprestimo"),
    pesquisarAluno: (dado: any) => ipcRenderer.invoke("pesquisar-aluno", dado),
    pesquisarLivro: (dado: any) => ipcRenderer.invoke("pesquisar-livro", dado),
    pesquisarEmprestimos: (dados: any) => ipcRenderer.invoke("pesquisar-emprestimos", dados),
    deleteAluno: (dado: any) => ipcRenderer.invoke("delete-aluno", dado),
    deleteLivro: (dado: any) => ipcRenderer.invoke("delete-livro", dado),
    deleteEmprestimo: (dado: any) => ipcRenderer.invoke("delete-emprestimo", dado),
    confirmarDevolucao: (dado: any) => ipcRenderer.invoke("confirmar-devolucao", dado),
    obterExportacao: (inicio?: string, fim?: string) => ipcRenderer.invoke("obter-exportacao", inicio, fim),
    registrarDebug: (origem: string, mensagem: string, detalhes?: string) => ipcRenderer.invoke("registrar-debug", origem, mensagem, detalhes),
    obterLogsDebug: () => ipcRenderer.invoke("obter-logs-debug"),
    limparLogsDebug: () => ipcRenderer.invoke("limpar-logs-debug"),
    copiarLogsDebug: () => ipcRenderer.invoke("copiar-logs-debug"),
    limparDados: (tipo: "movimentacoes" | "emprestimos" | "alunos" | "acervo") => ipcRenderer.invoke("limpar-dados", tipo),
    obterConfiguracao: () => ipcRenderer.invoke("obter-configuracao"),
    salvarConfiguracao: (dados: any) => ipcRenderer.invoke("salvar-configuracao", dados),
});
